/-
Copyright (c) 2025 Leopold Mayer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dora Kassabova, Leopold Mayer, Haoming Ning
-/
module

public import Mathlib.RingTheory.RegularLocalRing.AuslanderBuchsbaumSerre
public import Mathlib.RingTheory.RegularLocalRing.GlobalDimension
public import Mathlib.RingTheory.UniqueFactorizationDomain.Kaplansky

/-!

# Localization of Regular Local Ring is Regular

In this file, we establish the full version of Auslander-Buchsbaum-Serre criterion and its corollary
that localization of regular local ring is regular.

-/

@[expose] public section

universe u v

variable (R : Type u) [CommRing R] [IsDomain R] [IsRegularLocalRing R]
variable (n : ℕ)

#check Ring.KrullDimLE.isField_of_isDomain

notation "m" => IsLocalRing.maximalIdeal

open Localization

#check (m R)^2
example (x : R) : CommRing (Localization.Away x) := inferInstance
/- how to express f/x^n in R_x -/
example (x f : R) (n : ℕ) : (Localization.Away x) := Localization.mk f ⟨x^n, ⟨n, rfl⟩⟩

#check WfDvdMonoid.exists_factors

theorem isUniqueFactorizationDomain' (n : ℕ) : ∀ R : Type u, [CommRing R] → [IsDomain R]
    → [IsRegularLocalRing R] → (ringKrullDim R = n) → UniqueFactorizationMonoid R := by
  /- We will prove the unique factorization property by induction
    on the dimension of the regular local ring R -/
  induction n using Nat.strong_induction_on with
  | h n hn =>
  intros R _ _ _ hn
  cases n with
  /- If dim(R)=0, then R is a field and in particular a UFD -/
  | zero =>
  have HHH : Ring.KrullDimLE 0 R := by rw [Ring.krullDimLE_iff, hn]
  have H : IsField R := Ring.KrullDimLE.isField_of_isDomain
  have HH : IsPrincipalIdealRing R := IsField.isPrincipalIdealRing H
  apply PrincipalIdealRing.to_uniqueFactorizationMonoid
  /- Assume dim(R)>0 -/
  | succ n =>
  --let x ∈ m \ m^2
  have H1 : ∃ x, x ∈ (m R).carrier \ ((m R)^2).carrier  := sorry
  cases H1 with
  | intro x hx =>
  /- then R/(x) is regular -/
  have Hx : IsRegularLocalRing (R ⧸ Ideal.span {x}) := sorry
  /- hence a domain -/
  have Hx' : IsDomain (R ⧸ Ideal.span {x}) := isDomain_of_isRegularLocalRing _
  /- hence x is a prime element -/
  have hx_prime : Prime x := sorry
  rw [UniqueFactorizationMonoid.iff_exists_prime_mem_of_isPrime]
  intros p hp_ne_bot hp_prime
  /- we see that p_x=(y) for some y ∈ R_x -/
  have hp_princ : (p.map (algebraMap R (Away x))).IsPrincipal := sorry
  /- We can write y=x^ef for some f∈p and e∈Z. -/
  match hp_princ with
  | ⟨⟨y, hy⟩⟩ =>
  have hy : ∃ f : R, ∃ e : ℕ,
      f ∈ p ∧ y * (mk (x^e) ⟨1, one_mem _⟩) = (mk f ⟨1, one_mem _⟩) := sorry
  /- Factor f=a1…ar into irreducible elements of R -/
  rcases hy with ⟨f, e, hfp, hf⟩
  rcases WfDvdMonoid.exists_factors f (sorry : f ≠ 0) with ⟨a, ha_irr, ha_prod⟩
  /- Since p is prime, we see that ai∈p for some i. -/
  have ha : ∃ a' ∈ a, a' ∈ p := sorry
  rcases ha with ⟨a', ha'⟩
  /-  Since p_x=(y) is prime and a_i | y in R_x, it follows that
  p_x is generated by a_i in R_x, i.e., the image of a_i in R_x is prime
  -/
  have ha_gen : Away x ∙ y = Away x ∙ (mk a' ⟨1, one_mem _⟩) := sorry
  have ha'_prime_image : Prime (algebraMap R (Away x) a') := sorry
  /- As x is a prime element, we find that ai is prime in R -/
  have ha'_prime : Prime a' := sorry
  exact ⟨a', ha'.2, ha'_prime⟩



theorem isUniqueFactorizaitonDomainOfDimension (hn : ringKrullDim R = n) :
    UniqueFactorizationMonoid R := isUniqueFactorizationDomain' n R hn

instance isUniqueFactorizationDomain [IsRegularLocalRing R] : UniqueFactorizationMonoid R := sorry
